/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
package com.vp.bookstore.pojo;

import lombok.Data;

@Data
public class Afteruser implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5996558110637492928L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** arid */
    private Integer arid;

    /** arname */
    private String arname;

    /** arpassword */
    private String arpassword;

    /** bumen */
    private String bumen;

    /** quanxian */
    private String quanxian;

    /** danwei */
    private String danwei;

    /** address */
    private String address;

    /** phone */
    private String phone;

    /** email */
    private String email;

    /** qq */
    private String qq;


}