package com.vp.bookstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:35
 * @Version: 1.0
 */

import lombok.Data;

/**
 * 书类别表
 */
@Data
public class BookType implements java.io.Serializable{
    /** 版本号 */
    private static final long serialVersionUID = -6518188627038432257L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** booktypeId */
    private Integer booktype_id;

    /** booktypeName */
    private String booktype_name;
}
