package com.vp.bookstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:24
 * @Version: 1.0
 */

import lombok.Data;

import java.sql.Timestamp;

/**
 * 书籍信息表
 */
@Data
public class BookInfo implements java.io.Serializable{
    /** 版本号 */
    private static final long serialVersionUID = -8977923589642342968L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 书籍ID */
    private Integer bookId;

    /** 书籍名称 */
    private String bookName;

    /** 书的价格 */
    private Double bookPrice;

    /** 折扣等级 */
    private Double bookDiscount;

    /** 书折扣价 */
    private Double bookDiscountprice;

    /** 书的图片 */
    private String bookImg;

    /** 书的详情 */
    private String bookDetails;

    /** 书的状态1代表通过 */
    private Integer bookStatus;

    /** 书的类型 */
    private Integer booktypeId;

    /** 适合班级 */
    private Integer bookFitclass;

    /** 书的作者 */
    private String bookAuth;

    /** 上传用户 */
    private Integer userId;

    /** 是否可以兑换 */
    private Integer bookIsexchange;

    /** 出版社 */
    private String bookPress;

    /** 时间 */
    private Timestamp bookDate;

    /** 收藏数量 */
    private Integer bookCollection;

    /** 售出数量 */
    private Integer bookSell;

    /** 库存 */
    private Integer bookStock;
}
