package com.vp.bookstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:38
 * @Version: 1.0
 */

import lombok.Data;

/**
 * 收藏记录表
 */
@Data
public class Collection implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -267278765694823154L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 收藏表的ID */
    private Integer collection_id;

    /** bookId */
    private Integer book_id;

    /** userId */
    private Integer user_id;

}
