package com.vp.bookstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:39
 * @Version: 1.0
 */

import lombok.Data;

import java.sql.Timestamp;

/**
 * 评论表
 */
@Data
public class Comment implements java.io.Serializable{
    private static final long serialVersionUID = 5659758877323700536L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 评论表ID */
    private Integer commentId;

    /** bookId */
    private Integer bookId;

    /** userId */
    private Integer userId;

    /** 评论内容 */
    private String commentContent;

    /** 时间 */
    private Timestamp commentDate;
}
