package com.vp.bookstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 11:16
 * @Version: 1.0
 */

import lombok.Data;

import java.sql.Timestamp;

/**
 * 日志信息表
 */
@Data
public class Log implements java.io.Serializable{
    /** 版本号 */
    private static final long serialVersionUID = 5628999092542545126L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** logId */
    private Integer logId;

    /** 日志内容 */
    private String logContent;

    /** 谁产生的 */
    private Integer userId;

    /** 日志类别 */
    private Integer logType;

    /** 产生时间 */
    private Timestamp logDate;
}
