package com.vp.bookstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 13:44
 * @Version: 1.0
 */

import lombok.Data;

/**
 * 订单详情表
 */
@Data
public class OrderDetail implements java.io.Serializable{
    /** 版本号 */
    private static final long serialVersionUID = 2877664263938829980L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** orderdetailId */
    private Integer orderdetail_id;

    /** 订单表的id */
    private Integer order_id;

    /** 书的编号 */
    private Integer book_id;

    /** 数量 */
    private Integer book_number;
}
