package com.vp.bookstore.pojo;

/**
 * @Author: duYang
 * @Date: 2019/12/23 10:59
 * @Version: 1.0
 */

import lombok.Data;

/**
 * 用户密保表
 */
@Data
public class Protect implements java.io.Serializable{
    /** 版本号 */
    private static final long serialVersionUID = -500439162743751111L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 密保ID */
    private Integer protectId;

    /** 用户ID */
    private Integer userId;

    /** 密保问题 */
    private String protectProblem;

    /** 密保答案 */
    private String protectAnswer;
}
